version: '3'
services:
  web:
    image: nginx:latest
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    container_name: nginx
  php:
    build: php-7.0-fpm-custom
    links:
      - db
    volumes:
      - ./htdocs:/var/www/html
    container_name: php-fpm
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: mariadb
